# These are supported funding model platforms

github: [mochenxm]
patreon: mochenxm
open_collective: mochenxm
ko_fi: mochenxm
tidelift: npm/babel
community_bridge: cloud-foundry
liberapay: mochenxm
issuehunt: mochenxm
otechie: mochenxm
custom: ['link1', 'link2']
